# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_to_client.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server_to_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16server_to_client.proto\x12\x11\x64iscovery_service\"\x07\n\x05\x45mpty\"\x1f\n\x0cQueryRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x1f\n\x0bServerError\x12\x10\n\x08serverId\x18\x01 \x01(\x05\"Z\n\nQueryReply\x12\x10\n\x08serverId\x18\x01 \x01(\x05\x12\x10\n\x08serverIp\x18\x02 \x01(\t\x12\x12\n\nserverPort\x18\x03 \x01(\x05\x12\x14\n\x0cquerySuccess\x18\x04 \x01(\x08\x32\xb2\x01\n\x10\x44iscoveryService\x12L\n\nfindServer\x12\x1f.discovery_service.QueryRequest\x1a\x1d.discovery_service.QueryReply\x12P\n\x0fwarnServerError\x12\x1e.discovery_service.ServerError\x1a\x1d.discovery_service.QueryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_to_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=45
  _globals['_EMPTY']._serialized_end=52
  _globals['_QUERYREQUEST']._serialized_start=54
  _globals['_QUERYREQUEST']._serialized_end=85
  _globals['_SERVERERROR']._serialized_start=87
  _globals['_SERVERERROR']._serialized_end=118
  _globals['_QUERYREPLY']._serialized_start=120
  _globals['_QUERYREPLY']._serialized_end=210
  _globals['_DISCOVERYSERVICE']._serialized_start=213
  _globals['_DISCOVERYSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
