# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import server_to_client_pb2 as server__to__client__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in server_to_client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.findServer = channel.unary_unary(
                '/discovery_service.DiscoveryService/findServer',
                request_serializer=server__to__client__pb2.QueryRequest.SerializeToString,
                response_deserializer=server__to__client__pb2.QueryReply.FromString,
                _registered_method=True)
        self.warnServerError = channel.unary_unary(
                '/discovery_service.DiscoveryService/warnServerError',
                request_serializer=server__to__client__pb2.ServerError.SerializeToString,
                response_deserializer=server__to__client__pb2.QueryReply.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def findServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def warnServerError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'findServer': grpc.unary_unary_rpc_method_handler(
                    servicer.findServer,
                    request_deserializer=server__to__client__pb2.QueryRequest.FromString,
                    response_serializer=server__to__client__pb2.QueryReply.SerializeToString,
            ),
            'warnServerError': grpc.unary_unary_rpc_method_handler(
                    servicer.warnServerError,
                    request_deserializer=server__to__client__pb2.ServerError.FromString,
                    response_serializer=server__to__client__pb2.QueryReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'discovery_service.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('discovery_service.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def findServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/discovery_service.DiscoveryService/findServer',
            server__to__client__pb2.QueryRequest.SerializeToString,
            server__to__client__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def warnServerError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/discovery_service.DiscoveryService/warnServerError',
            server__to__client__pb2.ServerError.SerializeToString,
            server__to__client__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
