# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_to_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server_to_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16server_to_server.proto\x12\x10registry_service\"\x07\n\x05\x45mpty\"l\n\rRecordRequest\x12\x10\n\x08serverId\x18\x01 \x01(\x05\x12\x10\n\x08serverIp\x18\x02 \x01(\t\x12\x12\n\nserverPort\x18\x03 \x01(\x05\x12\x12\n\noverloaded\x18\x04 \x01(\x08\x12\x0f\n\x07service\x18\x05 \x01(\t\"4\n\x0cRenewRequest\x12\x10\n\x08serverId\x18\x01 \x01(\x05\x12\x12\n\noverloaded\x18\x02 \x01(\x08\"\x1d\n\nQueryReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa8\x01\n\x0fRegistryService\x12J\n\tdiscovery\x12\x1f.registry_service.RecordRequest\x1a\x1c.registry_service.QueryReply\x12I\n\theartBeat\x12\x1e.registry_service.RenewRequest\x1a\x1c.registry_service.QueryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_to_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=44
  _globals['_EMPTY']._serialized_end=51
  _globals['_RECORDREQUEST']._serialized_start=53
  _globals['_RECORDREQUEST']._serialized_end=161
  _globals['_RENEWREQUEST']._serialized_start=163
  _globals['_RENEWREQUEST']._serialized_end=215
  _globals['_QUERYREPLY']._serialized_start=217
  _globals['_QUERYREPLY']._serialized_end=246
  _globals['_REGISTRYSERVICE']._serialized_start=249
  _globals['_REGISTRYSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
