# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import server_to_server_pb2 as server__to__server__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in server_to_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.discovery = channel.unary_unary(
                '/registry_service.RegistryService/discovery',
                request_serializer=server__to__server__pb2.RecordRequest.SerializeToString,
                response_deserializer=server__to__server__pb2.QueryReply.FromString,
                _registered_method=True)
        self.heartBeat = channel.unary_unary(
                '/registry_service.RegistryService/heartBeat',
                request_serializer=server__to__server__pb2.RenewRequest.SerializeToString,
                response_deserializer=server__to__server__pb2.QueryReply.FromString,
                _registered_method=True)


class RegistryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def discovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'discovery': grpc.unary_unary_rpc_method_handler(
                    servicer.discovery,
                    request_deserializer=server__to__server__pb2.RecordRequest.FromString,
                    response_serializer=server__to__server__pb2.QueryReply.SerializeToString,
            ),
            'heartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartBeat,
                    request_deserializer=server__to__server__pb2.RenewRequest.FromString,
                    response_serializer=server__to__server__pb2.QueryReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'registry_service.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('registry_service.RegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def discovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry_service.RegistryService/discovery',
            server__to__server__pb2.RecordRequest.SerializeToString,
            server__to__server__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def heartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry_service.RegistryService/heartBeat',
            server__to__server__pb2.RenewRequest.SerializeToString,
            server__to__server__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
